package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations will be copied through when generating and any unknown code
// will be moved to the end.
//
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"errors"

	"product-service/graph/generated"
	"product-service/graph/model"
)

// =====================
// MUTATION RESOLVERS
// =====================

func (r *mutationResolver) CreateProduct(
	ctx context.Context,
	input model.CreateProductInput,
) (*model.Product, error) {

	req := toServiceCreate(input)

	p, err := r.ProductService.CreateProduct(ctx, req)
	if err != nil {
		return nil, err
	}

	return toGraphProduct(p), nil
}

func (r *mutationResolver) UpdateProduct(
	ctx context.Context,
	id string,
	input model.UpdateProductInput,
) (*model.Product, error) {

	// TEMPORARY IMPLEMENTATION
	// (prevents compile error, logic can be added later)
	return nil, errors.New("updateProduct not implemented yet")
}

func (r *mutationResolver) DeleteProduct(
	ctx context.Context,
	id string,
) (bool, error) {

	return r.ProductService.DeleteProduct(ctx, id)
}

// =====================
// QUERY RESOLVERS
// =====================

func (r *queryResolver) Products(
	ctx context.Context,
) ([]*model.Product, error) {

	products, err := r.ProductService.GetProducts(ctx)
	if err != nil {
		return nil, err
	}

	result := make([]*model.Product, 0, len(products))
	for _, p := range products {
		result = append(result, toGraphProduct(p))
	}

	return result, nil
}

func (r *queryResolver) Product(
	ctx context.Context,
	id string,
) (*model.Product, error) {

	p, err := r.ProductService.GetProductByID(ctx, id)
	if err != nil {
		return nil, err
	}

	return toGraphProduct(p), nil
}

// =====================
// ROOT RESOLVERS
// =====================

func (r *Resolver) Mutation() generated.MutationResolver {
	return &mutationResolver{r}
}

func (r *Resolver) Query() generated.QueryResolver {
	return &queryResolver{r}
}

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }




// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//  - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//    it when you're done.
//  - You have helper methods in this file. Move them out to keep these resolver files clean.
/*
	type Resolver struct {
	productService service.ProductService
}
func NewResolver(productService service.ProductService) *Resolver {
	return &Resolver{productService: productService}
}
func (r *Resolver) CreateProduct(ctx context.Context, input model.CreateProductInput) (*model.Product, error) {
	req := service.CreateProductRequest{
		Name:        input.Name,
		Description: input.Description,
		Price:       input.Price,
		Stock:       input.Stock,
	}

	product, err := r.productService.CreateProduct(ctx, req)
	if err != nil {
		return nil, err
	}

	return &model.Product{
		ID:          product.ID,
		Name:        product.Name,
		Description: product.Description,
		Price:       product.Price,
		Stock:       product.Stock,
		CreatedAt:   product.CreatedAt.Format("2006-01-02T15:04:05Z07:00"),
		UpdatedAt:   product.UpdatedAt.Format("2006-01-02T15:04:05Z07:00"),
	}, nil
}
func (r *Resolver) UpdateProduct(ctx context.Context, id string, input model.UpdateProductInput) (*model.Product, error) {
	req := service.UpdateProductRequest{
		Name:        input.Name,
		Description: input.Description,
		Price:       input.Price,
		Stock:       input.Stock,
	}

	product, err := r.productService.UpdateProduct(ctx, id, req)
	if err != nil {
		return nil, err
	}

	return &model.Product{
		ID:          product.ID,
		Name:        product.Name,
		Description: product.Description,
		Price:       product.Price,
		Stock:       product.Stock,
		CreatedAt:   product.CreatedAt.Format("2006-01-02T15:04:05Z07:00"),
		UpdatedAt:   product.UpdatedAt.Format("2006-01-02T15:04:05Z07:00"),
	}, nil
}
func (r *Resolver) DeleteProduct(ctx context.Context, id string) (bool, error) {
	return r.productService.DeleteProduct(ctx, id)
}
func (r *Resolver) Products(ctx context.Context) ([]*model.Product, error) {
	products, err := r.productService.GetProducts(ctx)
	if err != nil {
		return nil, err
	}

	var result []*model.Product
	for _, p := range products {
		result = append(result, &model.Product{
			ID:          p.ID,
			Name:        p.Name,
			Description: p.Description,
			Price:       p.Price,
			Stock:       p.Stock,
			CreatedAt:   p.CreatedAt.Format("2006-01-02T15:04:05Z07:00"),
			UpdatedAt:   p.UpdatedAt.Format("2006-01-02T15:04:05Z07:00"),
		})
	}

	return result, nil
}
func (r *Resolver) Product(ctx context.Context, id string) (*model.Product, error) {
	product, err := r.productService.GetProductByID(ctx, id)
	if err != nil {
		return nil, err
	}

	return &model.Product{
		ID:          product.ID,
		Name:        product.Name,
		Description: product.Description,
		Price:       product.Price,
		Stock:       product.Stock,
		CreatedAt:   product.CreatedAt.Format("2006-01-02T15:04:05Z07:00"),
		UpdatedAt:   product.UpdatedAt.Format("2006-01-02T15:04:05Z07:00"),
	}, nil
}
*/
